### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by Draiken23** [RetroHursty69/HurstyThemes#4]
I copied the script just as posted and got this error. Is there something I am doing wrong?

pi@retropie:~ $ wget https://raw.githubusercontent.com/RetroHursty69/HurstyThemes/master/install.sh
--2019-01-18 17:51:06--  https://raw.githubusercontent.com/RetroHursty69/HurstyThemes/master/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.48.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.48.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1960 (1.9K) [text/plain]
Saving to: ‘install.sh.2’

install.sh.2        100%[===================>]   1.91K  --.-KB/s    in 0s

2019-01-18 17:51:07 (8.60 MB/s) - ‘install.sh.2’ saved [1960/1960]

pi@retropie:~ $ chmod +x "install.sh"
pi@retropie:~ $ ./install.sh
./install.sh: line 1: syntax error near unexpected token `<'
./install.sh: line 1: `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><meta http-equiv="refresh" content="0;url=http://finder.cox.net/main?ParticipantID=96e687opkbv4scrood8k84drs6gw5duf&FailedURI=http%3A%2F%2Fraw.githubuseercontent.com%2FRetroHursry69%2FHurstyThemes%2Fmaster%2Finstall.sh&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us"/><script type="text/javascript">url="http://finder.cox.net/main?ParticipantID=96e687opkbv4scrood8k84drs6gw5duf&FailedURI=http%3A%2F%2Fraw.githubuseercontent.com%2FRetroHursry69%2FHurstyThemes%2Fmaster%2Finstall.sh&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us";if(top.location!=location){var w=window,d=document,e=d.documentElement,b=d.body,x=w.innerWidth||e.clientWidth||b.clientWidth,y=w.innerHeight||e.clientHeight||b.clientHeight;url+="&w="+x+"&h="+y;}window.location.replace(url);</script></head><body></body></html>'

**Comment by RetroHursty69** [comment]
Looks like you already had a file on your Pi called install.sh so it saved the file as install.sh.2.

So you go to command line and do these 2 steps:

chmod +x "install.sh.2" <enter>

./install.sh.2  <enter>

**Comment by Draiken23** [comment]
Thanks that worked
