### ISSUE TITLE
Use #HOME instead of /home/pi

### ISSUE THREAD

**Issue by gsemet** [RetroHursty69/HurstyThemes#5]
I use retrosmc to install retropi on OSMC and the user it in /home/osmc and not /home/pi. Would be cool do not hardcode /home/pi.

thanks

**Comment by RetroHursty69** [comment]
Sorry I don't understand? This is created for RetroPie on Raspberry Pi so why would it be done any different? It is not designed to be used any other way.

**Comment by gsemet** [comment]
Yes, I understand. Retro pie works great on Osmc (which is a Raspberry Pi kodi distribution), and there is a script called Retosmc to install Retropie quite easily.
The only thing is that the user is « osmc » instead of « pi », so your script does not work straight ahead. I ll try to make a pull request, should be enough to grep « /home/pi » by « $HOME »

**Comment by RetroHursty69** [comment]
Happy for you to branch and make a version for yourself. I don't think I will change my branch.
