### ISSUE TITLE
Syntax error in install.sh - line 23

### ISSUE THREAD

**Issue by brettstark73** [RetroHursty69/HurstyThemes#9]
pi@retropie:~ $ ./install.sh 
Cloning into '/tmp/hursty'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 350 (delta 39), reused 44 (delta 21), pack-reused 287
Receiving objects: 100% (350/350), 736.77 KiB | 0 bytes/s, done.
Resolving deltas: 100% (216/216), done.
./install.sh: line 23: syntax error near unexpected token `else'
./install.sh: line 23: `else'

**Comment by dmmarti** [comment]
Ah, I see what's going on.  You already have a scripts folder, so linux doesn't like the #nothing line (currently line 22).

This'll fix it:

if [[ -d "/home/pi/scripts" ]]; then
     echo "exists" > /dev/null
else
    mkdir /home/pi/scripts
fi

Change the line for 
    #nothing
 to be 
echo "exists" > /dev/null
 instead so linux will do something when the script folder already exists.

**Comment by RetroHursty69** [comment]
The script has been updated with a fix now.

**Comment by brettstark73** [comment]
Thx!!
